# Generated by Django 3.0.6 on 2020-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0004_reviews_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя'),
        ),
    ]
